### PR TITLE
migrate to pipenv for better package dependency

### LINKED ISSUE #35: Migrate to pipenv
## Description

Managing python requirements file manually is not a good idea, as it leads to problems down the road. Switch to `pipenv` https://realpython.com/pipenv-guide/

### PR DESCRIPTION
**Pull request by nkilm**
### Fixes #35 

Use `pipenv` for package dependency.

### Changes

Added `Pipfile` and `.lock` file

## How to test

Describe the steps required to test the changes proposed in the pull request.

1. Create a Virtual Environment using the following command
```bash
pipenv install --python=3.9.0

# it will detect requirements.txt file and install all packages
```
2. Activate the shell
```bash
pipenv shell

# check if venv is activated or not
pip -V
```
3. Start the project
```bash
python3 command_line_script --path filePath --delay delay_before_typing
```

### CODE REVIEW

**Comment by Mr-Sunglasses** [comment]
@nkilm Thanks for the Contribution, Can you please update the steps in `README.md`

**Comment by nkilm** [comment]
@Mr-Sunglasses Alright

**Comment by Mr-Sunglasses** [comment]
@tushar5526 I have tested the changes and it LGTM.

image

**Review by Mr-Sunglasses — APPROVED** [review]
@tushar5526 I have tested the changes and it LGTM.

image

**Review by a-r-r-o-w — COMMENTED** [review]
Looks good!

**Pull request merged**
